language: php
sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2

matrix:
    fast_finish: true

install:
    - composer self-update
    - composer update
    - chmod +x ./run-tests.sh

script:
    - vendor/bin/phpunit
    - vendor/bin/psalm
